### PR TITLE
Use smokestack

### PR DESCRIPTION
**Pull request by freeman-lab**
This PR switches from `testron` to `smokestack` for the unit tests. It also fixes a few cases of non-standard formatting.

### CODE REVIEW

**Comment by freeman-lab** [comment]
cc @rreusser

**Comment by rreusser** [comment]
Ah, cool. Yeah, testron seemed to run just fine but just failed silently, so wasn't immediately apparent how to get it running. I'll give it a try!

**Comment by freeman-lab** [comment]
Yup yup, I've had the exact same experience with testron and debugging usually involved messing with electron versions, which is always ugh. With this one, you'll need an alias for `chrome` e.g. `alias chrome='open "/Applications/Google Chrome.app"'` but otherwise it works reliably for me.

**Comment by rreusser** [comment]
Hmm… I had:

```
$ cat /usr/local/bin/chrome
#!/bin/sh
open -a "Google Chrome" $1
```

but yeah, it's probably something fairly simple.

**Pull request merged**
