### PR TITLE
Real quick button input

### PR DESCRIPTION
**Pull request by rreusser**
Was a big fan of datgui, but it's not so well maintained anymore. Thanks so much for this! In the spirit of filling in some datgui gaps, I added a button control. It needs documentation, but I thought I'd run it past you for feedback. Syntax is:

``` javascript
{type: 'button', label: 'gimme an alert', action: function () { alert('hello!'); }}
```

Live example here: https://rreusser.github.io/regl-smooth-life/

Layout isn't perfect to suggest that it's a button. A hover state would probably be nice, but wasn't sure whether to do color computation or just add a new theme color.

### CODE REVIEW

**Comment by freeman-lab** [comment]
Cool thanks @rreusser! Glad you like it, I was also a fan of datgui and had exactly the same thoughts. Also, awesome `regl` demo! 

This looks great to me, I like the style a lot as is. I initially might have thought to make it less wide like this:

screen shot 2016-05-16 at 11 19 43 pm


But now that I see both I prefer the full width.

How do you think the state of this one should be represented in the `panel.on('input', cb(data))` event, if at all? It's a slightly different kind of input than the rest.

cc @mikolalysenko who I think was interested in a similar feature (and will probably like the demo!)

**Comment by rreusser** [comment]
Hmm… yeah, maybe instead of a callback, could instead pass this through the event emitter:

```javascript
panel.on('buttonpress', function (label) { ... });
```

Would probably be a better fit with the current API. Perhaps `'input`` shouldn't be triggered in this case.

**Comment by freeman-lab** [comment]
Hm looking at it more, I kinda think we should just make the `action` a passed option exactly as you have it, and skip the button in the `input` event for now. It's a pretty natural way to specify the action, and seems ok that it's different because it's not really stateful the way the others are.

At some point it might be good to expose a scoped event for every item, so you can do `panel.on('button', cb)` `panel.on('slider', cb)` etc., but we can do that later.

So maybe update the README to include this and we'll merge it in? Thanks!

**Comment by rreusser** [comment]
Added docs and removed inputs with `type === 'button'` from the state object.

**Pull request closed without merging**
